title: Notes
description: Notas organizadas por data

# Defaults para notas
defaults:
  - scope:
      path: "notes"
    values:
      layout: post

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - AGENTS.md
