title: Notes
description: Notas organizadas por data
baseurl: /notes

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - AGENTS.md
